// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVaFM8_XfLhyfu1o3gbS5PdLKCCzip3C8',
    appId: '1:240792444325:web:17aa367c83b72fe6ac1c4c',
    messagingSenderId: '240792444325',
    projectId: 'chat-app-5365a',
    authDomain: 'chat-app-5365a.firebaseapp.com',
    storageBucket: 'chat-app-5365a.appspot.com',
    measurementId: 'G-T171BRB0Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArqvkAeUPQY4ggh_xQbHdRn2tX4rQNz1Y',
    appId: '1:240792444325:android:8f9f812a691f6af7ac1c4c',
    messagingSenderId: '240792444325',
    projectId: 'chat-app-5365a',
    storageBucket: 'chat-app-5365a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB299f_Rj_cM4dOneMMhtf1EgOfZ7E-E5Q',
    appId: '1:240792444325:ios:16fb1ca1af05f8beac1c4c',
    messagingSenderId: '240792444325',
    projectId: 'chat-app-5365a',
    storageBucket: 'chat-app-5365a.appspot.com',
    iosClientId: '240792444325-5deauu2vjfphp9k6vnnb5oqp88bv1i1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB299f_Rj_cM4dOneMMhtf1EgOfZ7E-E5Q',
    appId: '1:240792444325:ios:16fb1ca1af05f8beac1c4c',
    messagingSenderId: '240792444325',
    projectId: 'chat-app-5365a',
    storageBucket: 'chat-app-5365a.appspot.com',
    iosClientId: '240792444325-5deauu2vjfphp9k6vnnb5oqp88bv1i1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
